Dfs solver Update
pbosler/lpm pull request #143
Opened 2024-09-23 18:11 UTC by michaelchiwere1

Fixed the Segfault issue with the DFS solver, and added RK3 and RK4 integration and double dot product.

2024-09-24 18:07 UTC, pbosler requested changes

2024-09-24 18:07 UTC, pbosler commented on src/dfs/dfs_swe_vort2velocity_to_ddproduct.cpp
For the future (not this pull request):

When you define views in a function like this (lines 14--18, for example), these views are allocated and deallocated every time this function is called.   If this function, and others like it, are called at every time step this style of programming can slow down your code a lot.   Instead of a `namespace` with functions, try a `class`.  

The views would be member variables and these functions become member functions; the views will persist for as long as the class instance persists -- i.e., one deallocation/allocation of each view for as long as the grid doesn't change.

Let's save this kind of refactor for a separate pull request.   We'll merge this one as soon as it's correct and tests are passing.

2024-09-24 21:30 UTC, michaelchiwere1 commented on src/dfs/dfs_rhs_new.cpp
> +        int nthreads = 8;	//omp_get_max_threads();
Replaced.

2024-09-24 21:30 UTC, michaelchiwere1 commented on src/.vscode/settings.json
Removed.

2024-09-24 21:31 UTC, michaelchiwere1 commented on src/dfs/dfs_rhs_new.hpp
> +#include "omp.h"
Removed "amp.h"

2024-09-24 21:32 UTC, michaelchiwere1 commented on src/dfs/dfs_solve_new.cpp
> +        view_3d<Real> Llo("Lok", nrows, nrows, mid);
I added the comment here.

2024-10-16 15:32 UTC, pbosler approved these changes
Approving.   Jobs are passing on the auto-test workflow.

2024-10-16 15:32 UTC, merged